POST
https://siltechtz.com/app/smsapi/index.php
&key=35E4C86A0C1A31
&campaign=1
&routeid=10
&type=text
&contacts=255620296750,255752748674
&senderid=15076
&msg=I wanna do some delivery report testing 2
%%%

# Duration: 1222 ms
# URL: https://siltechtz.com/app/smsapi/index.php?&key=35E4C86A0C1A31&campaign=1&routeid=10&type=text&contacts=255620296750%2C255752748674&senderid=15076&msg=I+wanna+do+some+delivery+report+testing+2

# HTTP/1.1 200 OK

@Date: Sat, 29 Feb 2020 05:58:04 GMT
@Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16
@X-Powered-By: PHP/5.4.16
@Content-Length: 38
@Keep-Alive: timeout=5, max=100
@Connection: Keep-Alive
@Content-Type: text/html; charset=UTF-8

SMS-SHOOT-ID/br_solutions5e59fd6c452c9