GET
https://siltechtz.com/app/miscapi/35E4C86A0C1A31/getDLR/br_solutions5e59fd6c452c9
%%%

# Duration: 1268 ms
# URL: https://siltechtz.com/app/miscapi/35E4C86A0C1A31/getDLR/br_solutions5e59fd6c452c9

# HTTP/1.1 200 OK

@Date: Sat, 29 Feb 2020 05:58:23 GMT
@Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16
@X-Powered-By: PHP/5.4.16
@Content-Length: 136
@Keep-Alive: timeout=5, max=100
@Connection: Keep-Alive
@Content-Type: text/html; charset=UTF-8

[{"MSISDN":"255620296750","DLR":"Delivered","DESC":"Delivered"},{"MSISDN":"255752748674","DLR":"Operator Submitted","DESC":"Delivered"}]